---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AdminsGroupName:
    Description: 'Name of the admins IAM user group'
    Type: String
    Default: admins
  BucketName:
    Description: 'Name of the S3 bucket'
    Type: String
    Default: notes-lnd-brk
  AwsRegion:
    Description: 'AWS Region'
    Type: String
    Default: us-west-2

Resources:
  NotesReaderPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: notesReader
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3BucketActions
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:ListAllMyBuckets
              - s3:ListBucketVersions
            Resource: "arn:aws:s3:::*"
          - Sid: S3ObjectActions
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: "arn:aws:s3:::*/*"

  NotesReaderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: notesReader
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref NotesReaderPolicy

  NotesWriterPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: notesWriter
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3ObjectActions
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:DeleteObjectVersion
            Resource: "arn:aws:s3:::*/*"

  NotesWriterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: notesWriter
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref NotesWriterPolicy
        - !Ref NotesReaderPolicy

  AssumeNotesReaderRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: assumeNotesReaderRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: !GetAtt NotesReaderRole.Arn
      Groups:
        - !Ref AdminsGroupName

  AssumeNotesWriterRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: assumeNotesWriterRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: !GetAtt NotesWriterRole.Arn
      Groups:
        - !Ref AdminsGroupName

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowAdminsAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:role/${AdminsGroupName}"
            Action:
              - s3:*
            Resource:
              - !Sub
                - ${bucketArn}/*
                - bucketArn: !GetAtt S3Bucket.Arn
              - !GetAtt S3Bucket.Arn
          - Sid: AllowNotesWriterAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt NotesWriterRole.Arn
            Action:
              - s3:ListBucket
              - s3:ListBucketVersions
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
              - s3:DeleteObject
              - s3:DeleteObjectVersion
            Resource:
              - !Sub
                - ${bucketArn}/*
                - bucketArn: !GetAtt S3Bucket.Arn
              - !GetAtt S3Bucket.Arn
          - Sid: AllowNotesReaderAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt NotesReaderRole.Arn
            Action:
              - s3:ListBucket
              - s3:ListBucketVersions
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - !Sub
                - ${bucketArn}/*
                - bucketArn: !GetAtt S3Bucket.Arn
              - !GetAtt S3Bucket.Arn

Outputs:
  NotesReaderRoleArn:
    Value: !GetAtt NotesReaderRole.Arn
  NotesWriterRoleArn:
    Value: !GetAtt NotesWriterRole.Arn
